name: Go Build for Multiple Platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]  # Multiple OS platforms
        arch: [ amd64, arm ]  # Added ARM support for Raspberry Pi 3B+
        exclude:
          - os: macos-latest
            arch: arm  # ❌ Remove invalid macOS/ARM pair

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Build the project
      run: |
        # Determine GOOS based on matrix OS
        case "${{ matrix.os }}" in
          ubuntu-latest) GOOS=linux ;;
          windows-latest) GOOS=windows ;;
          macos-latest) GOOS=darwin ;;
          *) echo "Unsupported OS" && exit 1 ;;
        esac

        GOARCH=${{ matrix.arch }}
        
        # Set GOARM flag for ARM builds (for Raspberry Pi)
        if [ "$GOARCH" = "arm" ]; then
          GOARM=7
        fi

        echo "Building for $GOOS $GOARCH GOARM=${GOARM:-}"

        # Define build output directory
        BUILD_DIR="build/$GOOS/$GOARCH"
        mkdir -p $BUILD_DIR

        # Set output filename based on OS
        OUTPUT_NAME="untisDSB${{ matrix.os == 'windows-latest' && '.exe' || '' }}"

        # Build the project
        env GOOS=$GOOS GOARCH=$GOARCH GOARM=${GOARM:-} go build -o $BUILD_DIR/$OUTPUT_NAME main.go

    - name: Test
      run: go test -v ./...

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: untisDSB-${{ matrix.os }}-${{ matrix.arch }}
        path: build/${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' }}/${{ matrix.arch }}/untisDSB*
        if-no-files-found: error  # Fail workflow if build output is missing

    - name: List build artifacts
      run: ls -R build

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: build/

    - name: List downloaded files
      run: |
        echo "Downloaded build artifacts:"
        ls -R build/
        echo "Included Tampermonkey scripts:"
        ls -R tampermonkey/ || echo "No Tampermonkey scripts found."

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # Use the pushed tag as the release tag
        files: |
          build/linux/amd64/untisDSB
          build/linux/arm/untisDSB
          build/windows/amd64/untisDSB.exe
          build/darwin/amd64/untisDSB
          tampermonkey/*.user.js
